name: vadim_dum
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  marquee: ^2.2.3
  flutter_hooks: ^0.20.5
  flutter_blurhash: ^0.7.0
  animated_text_kit: ^4.2.2
  dio: ^5.5.0+1
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/data/pictures/myp2.jpg
    - lib/data/pictures/kometa/db1.png
    - lib/data/pictures/kometa/desk1.png
    - lib/data/pictures/kometa/desk2.png
    - lib/data/pictures/kometa/desk3.png
    - lib/data/pictures/kometa/desk4.png
    - lib/data/pictures/kometa/mob1.png
    - lib/data/pictures/kometa/mob2.png
    - lib/data/pictures/kometa/mob3.png
    - lib/data/pictures/kometa/mob4.png
    - lib/data/pictures/kometa/mob5.png
    - lib/data/pictures/kometa/mob6.png
    - lib/data/pictures/kometa/mob7.png
    - lib/data/pictures/kometa/mob8.png
    - lib/data/pictures/kometa/mob9.png
    - lib/data/pictures/kometa/mob10.png
    - lib/data/pictures/kometa/mob11.png
    - lib/data/pictures/kometa/mob12.png
    - lib/data/pictures/kometa/mob13.png

  fonts:
    - family: Caravan
      fonts:
        - asset: fonts/Caravan.ttf
    - family: RubikMonoOne
      fonts:
        - asset: fonts/RubikMonoOne-Regular.ttf